name: Dockerized CI pipeline

on: push

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install dependencies
        run: npm install

      - name: run lint
        run: npm run lint
        continue-on-error: true

      - name: run unit tests
        run: npm run test

      - name: build static files
        run: npm run build

      - name: rename build folder for Docker
        run: mv build dist

      - name: log in GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner | toLower }}/react-app-cicd:${{ github.sha }}
            ghcr.io/${{ github.repository_owner | toLower }}/react-app-cicd:latest
